# Generated by Django 4.0.2 on 2022-04-11 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('Requisition Form', 'Requisition Form')], default='Requisition Form', max_length=20)),
                ('date', models.DateTimeField()),
                ('service_requested', models.TextField()),
                ('other_service', models.TextField(blank=True, null=True)),
                ('reason_for_request', models.TextField()),
                ('resp_dir_descision', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('resp_dir_descision_comments', models.TextField(blank=True, null=True)),
                ('dss_director_descision', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('dss_director_comments', models.TextField(blank=True, null=True)),
                ('mangaer_ict_descision', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('mangaer_ict_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
