# Generated by Django 4.0.2 on 2022-04-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='dss_director_descision',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='mangaer_ict_descision',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='resp_dir_descision',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=11),
        ),
    ]
