# Generated by Django 4.0.4 on 2022-04-27 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 11, 20, 45, 576693)),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='end_time',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
