# Generated by Django 4.0.4 on 2022-04-27 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0003_alter_requisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 11, 32, 0, 658654)),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='end_time',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
