# Generated by Django 4.0.4 on 2022-04-27 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0006_alter_requisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 11, 53, 53, 510994)),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='end_time',
            field=models.CharField(blank=True, default='Not Stated', max_length=20, null=True),
        ),
    ]
