# Generated by Django 4.0.4 on 2022-04-27 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0007_alter_requisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 12, 1, 32, 133331)),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='end_time',
            field=models.TextField(blank=True, choices=[('None', 'None')], default='None', null=True),
        ),
    ]
