# Generated by Django 4.0.4 on 2022-04-27 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0008_alter_requisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 12, 3, 25, 278543)),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='end_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
