# Generated by Django 4.0.4 on 2022-04-27 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0011_alter_requisitionform_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionform',
            old_name='mangaer_ict_comments',
            new_name='manager_ict_comments',
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 12, 48, 38, 870542)),
        ),
    ]
