# Generated by Django 4.0.4 on 2022-04-27 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0012_rename_mangaer_ict_comments_requisitionform_manager_ict_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 10, 29, 27, 309964)),
        ),
    ]
