# Generated by Django 4.0.4 on 2022-04-27 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0002_alter_form_form_name'),
        ('ict', '0018_alter_requisitionform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 10, 42, 42, 560612)),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='form_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.form'),
        ),
    ]
