# Generated by Django 4.0.4 on 2022-04-28 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0019_alter_requisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 11, 20, 3, 683516)),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='form_name',
            field=models.CharField(choices=[('Requisition Form', 'Requisition Form')], default='Requisition Form', max_length=20),
        ),
    ]
