# Generated by Django 4.0.4 on 2022-04-28 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0020_alter_requisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 14, 57, 10, 191458)),
        ),
    ]
