# Generated by Django 4.0.4 on 2022-04-28 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0021_alter_requisitionform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 14, 58, 35, 49521)),
        ),
    ]
