# Generated by Django 4.0.4 on 2022-05-03 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('ICT_Manager', 'ICT Manager'), ('DSS_Director', 'DSS Director'), ('FRD_Director', 'FRD Director'), ('FMD_Director', 'FMD Director'), ('ERD_Director', 'ERD Director'), ('DG', 'DG'), ('GOV', 'GOV'), ('Staff', 'Staff')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('GOV', 'GOV'), ('DSS', 'DSS'), ('FRD', 'FRD'), ('FMD', 'FMD'), ('ERD', 'ERD')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
