# Generated by Django 4.0.4 on 2022-04-28 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('ICT_Manger', 'ICT Manager'), ('DSS_Director', 'DSS Director'), ('FRD_Director', 'FRD Director'), ('FMD_Director', 'FMD Director'), ('ERD_Director', 'ERD Director'), ('DG', 'DG'), ('GOV', 'GOV'), ('Staff', 'Staff')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
