# Generated by Django 4.0.4 on 2022-05-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_department_department_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='department',
        ),
    ]
