# Generated by Django 4.0.2 on 2022-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[('ICT_Manager', 'ICT Manager'), ('DSS_Director', 'DSS Director'), ('FRD_Director', 'FRD Director'), ('FMD_Director', 'FMD Director'), ('ERD_Director', 'ERD Director'), ('GOV', 'GOV'), ('Staff', 'Staff')], max_length=20),
        ),
    ]
