# Generated by Django 4.0.4 on 2022-04-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_roles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[('ICT_Manager', 'ICT Manager'), ('DSS_Director', 'DSS Director'), ('FRD_Director', 'FRD Director'), ('FMD_Director', 'FMD Director'), ('ERD_Director', 'ERD Director'), ('DG', 'DG'), ('GOV', 'GOV'), ('Staff', 'Staff')], max_length=20),
        ),
    ]
