# Generated by Django 4.0.5 on 2022-07-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(choices=[('ICT_Unit', 'ICT Unit'), ('Director', 'Director')], max_length=20),
        ),
    ]
