# Generated by Django 4.0.4 on 2022-04-27 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ict', '0017_alter_requisitionform_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_description', models.TextField()),
                ('link', models.TextField()),
                ('form_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ict.requisitionform')),
            ],
        ),
    ]
