# Generated by Django 4.0.4 on 2022-04-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_name',
            field=models.TextField(),
        ),
    ]
