# Generated by Django 4.0.4 on 2022-04-28 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 10, 5, 29, 851016)),
        ),
    ]
