# Generated by Django 4.0.4 on 2022-04-29 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0003_alter_ictrequisitionform_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ictrequisitionform',
            old_name='dss_director_decision',
            new_name='dss_dir_decision',
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 13, 5, 43, 376722)),
        ),
    ]
