# Generated by Django 4.0.4 on 2022-04-29 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0004_rename_dss_director_decision_ictrequisitionform_dss_dir_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 14, 24, 39, 897979)),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='form_name',
            field=models.CharField(choices=[('ICT_Requisition_Form', 'ICT Requisition Form')], default='Requisition Form', max_length=20),
        ),
    ]
