# Generated by Django 4.0.4 on 2022-04-29 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0006_alter_ictrequisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 14, 51, 46, 636833)),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='form_name',
            field=models.CharField(choices=[('ICT_Requisition_Form', 'ICT Requisition Form')], default='ICT Requisition Form', max_length=20),
        ),
    ]
