# Generated by Django 4.0.2 on 2022-04-30 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0007_alter_ictrequisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 0, 15, 56, 810796)),
        ),
    ]
