# Generated by Django 4.0.4 on 2022-05-05 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0009_alter_ictrequisitionform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 15, 21, 263465)),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='form_name',
            field=models.CharField(choices=[('ICT Requisition Form', 'ICT Requisition Form')], default='ICT Requisition Form', max_length=20),
        ),
    ]
