# Generated by Django 4.0.4 on 2022-05-05 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0010_alter_ictrequisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 9, 40, 32, 481122)),
        ),
    ]
