# Generated by Django 4.0.4 on 2022-05-09 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ictrequisitionform',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 14, 5, 28, 882769)),
        ),
    ]
