# Generated by Django 4.0.4 on 2022-05-09 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0002_rename_date_ictrequisitionform_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ictrequisitionform',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 14, 7, 36, 66895)),
        ),
    ]
