# Generated by Django 4.0.4 on 2022-05-09 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0003_ictrequisitionform_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 14, 16, 53, 580892)),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
