# Generated by Django 4.0.4 on 2022-05-09 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0004_alter_ictrequisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 14, 18, 21, 252892)),
        ),
    ]
