# Generated by Django 4.0.4 on 2022-05-09 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0005_alter_ictrequisitionform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ictrequisitionform',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 14, 20, 42, 469756)),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='end_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
