# Generated by Django 4.0.4 on 2022-05-09 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0006_ictrequisitionform_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ictrequisitionform',
            name='time',
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 14, 25, 9, 280437)),
        ),
    ]
