# Generated by Django 4.0.4 on 2022-05-09 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0007_remove_ictrequisitionform_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 16, 19, 51, 245030)),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='end_date',
            field=models.TimeField(null=True),
        ),
    ]
