# Generated by Django 4.0.4 on 2022-05-09 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0011_alter_ictrequisitionform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 16, 40, 40, 905395)),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
