# Generated by Django 4.0.5 on 2022-07-12 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0023_alter_ictrequisitionform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 17, 14, 3, 295683)),
        ),
    ]
