# Generated by Django 4.0.5 on 2022-07-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0025_ictrequisitionform_manager_ict_tasks_to_ict_staffs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisitionform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
