# Generated by Django 4.0.5 on 2022-07-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_unit_unit'),
        ('afterhours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterhoursform',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
    ]
