# Generated by Django 4.0.5 on 2022-07-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterhours', '0002_alter_afterhoursform_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterhoursform',
            name='department',
            field=models.CharField(max_length=6),
        ),
    ]
