# Generated by Django 4.0.5 on 2022-07-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterhours', '0003_alter_afterhoursform_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='form_name',
            new_name='Form_name',
        ),
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='service_requested',
            new_name='Purpose',
        ),
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='end_time',
            new_name='Purpose_Reason',
        ),
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='start_date',
            new_name='Start_date',
        ),
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='start_time',
            new_name='Start_time',
        ),
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='resp_dir_comments',
            new_name='Unit_OR_Section',
        ),
        migrations.RenameField(
            model_name='afterhoursform',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='afterhoursform',
            name='other_service',
        ),
        migrations.AddField(
            model_name='afterhoursform',
            name='Access_and_Network_Decission',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=11),
        ),
        migrations.AddField(
            model_name='afterhoursform',
            name='End_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afterhoursform',
            name='IT_Services',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
