# Generated by Django 4.0.5 on 2022-07-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterhours', '0004_rename_department_afterhoursform_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterhoursform',
            name='end_date',
        ),
        migrations.AddField(
            model_name='afterhoursform',
            name='End_date',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afterhoursform',
            name='Purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
